name: prod

on:
  push:
    branches:
      - master
jobs:
  test:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: bulds
            run: |
              docker build -t nik-weter/react-test -f ./client/Dockerfile.dev ./client
          - name: Run the build process with Docker
            run: |
              docker run -e CI=true nik-weter/react-test npm run test -- --coverage
          - name: docker login
            uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Build and push client
            uses: docker/build-push-action@v3
            with:
              context: ./client
              push: false
              tags: nikweter/multi-client:latest
          - name: Build and push server
            uses: docker/build-push-action@v3
            with:
              context: ./server
              push: false
              tags: nikweter/multi-client:latest
          - name: Build and push worker
            uses: docker/build-push-action@v3
            with:
              context: ./worker
              push: false
              tags: nikweter/multi-worker:latest
          - name: Build and push nginx
            uses: docker/build-push-action@v3
            with:
              context: ./nginx
              push: false
              tags: nikweter/multi-nginx:latest
